# Page ranking

In [5]:
import numpy as np

def build_transition_matrix(filename):
    with open(filename, 'r') as file:
        links = file.readlines()

    pages = set()
    for link in links:
        parts = link.strip().split()
        if not parts:
            continue
        if len(parts) < 2:
            print("error formatting!")
            continue
        pages.add(parts[0])
        pages.update(parts[1:])

    pages = list(pages)
    page_index = {page: i for i, page in enumerate(pages)}
    num_pages = len(pages)
    
    M = np.zeros((num_pages, num_pages))
    
    for link in links:
        parts = link.strip().split()
        if not parts or len(parts) < 2:
            continue
        source_index = page_index[parts[0]]
        num_links = len(parts) - 1
        if num_links > 0:
            for target in parts[1:]:
                target_index = page_index[target]
                M[target_index][source_index] = 1.0 / num_links

    print("Transition Matrix:")
    print(M)
    return M, page_index, pages

def matrix_vector_multiply(matrix, vector):
    result = np.dot(matrix, vector)
    print('\n')
    print("Matrix-Vector Multiplication Result:")
    print(result)
    return result

def pagerank(M, num_iterations=10, damping_factor=0.85):
    num_pages = M.shape[0]
    rank_vector = np.ones(num_pages) / num_pages
    for iteration in range(num_iterations):
        new_rank_vector = (1 - damping_factor) / num_pages + damping_factor * \
                          matrix_vector_multiply(M, rank_vector)
        print('\n')
        print(f"Iteration {iteration + 1}:\n")
        print(new_rank_vector)
        rank_vector = new_rank_vector
    return rank_vector

def print_pagerank_scores(rank_vector, page_index):
    index_page = {v: k for k, v in page_index.items()}
    sorted_pages = sorted(((index_page[i], rank) for i, rank in enumerate(rank_vector)), 
                          key=lambda x: -x[1])
    print("PageRank Scores:")
    for page, score in sorted_pages:
        print(f"{page}: {score}")

if __name__ == "__main__":
    M, page_index, pages = build_transition_matrix('links.txt')
    rank_vector = pagerank(M)
    print_pagerank_scores(rank_vector, page_index)


Transition Matrix:
[[0.  0.5 1. ]
 [1.  0.  0. ]
 [0.  0.5 0. ]]


Matrix-Vector Multiplication Result:
[0.5        0.33333333 0.16666667]


Iteration 1:

[0.475      0.33333333 0.19166667]


Matrix-Vector Multiplication Result:
[0.35833333 0.475      0.16666667]


Iteration 2:

[0.35458333 0.45375    0.19166667]


Matrix-Vector Multiplication Result:
[0.41854167 0.35458333 0.226875  ]


Iteration 3:

[0.40576042 0.35139583 0.24284375]


Matrix-Vector Multiplication Result:
[0.41854167 0.40576042 0.17569792]


Iteration 4:

[0.40576042 0.39489635 0.19934323]


Matrix-Vector Multiplication Result:
[0.39679141 0.40576042 0.19744818]


Iteration 5:

[0.3872727  0.39489635 0.21783095]


Matrix-Vector Multiplication Result:
[0.41527913 0.3872727  0.19744818]


Iteration 6:

[0.40298726 0.37918179 0.21783095]


Matrix-Vector Multiplication Result:
[0.40742185 0.40298726 0.1895909 ]


Iteration 7:

[0.39630857 0.39253917 0.21115226]


Matrix-Vector Multiplication Result:
[0.40742185 0.3963085

In [6]:
import numpy as np
import numpy.linalg as la

L = np.array([[0, 1/2, 1/3, 0, 0, 0],
              [1/3, 0, 0, 0, 1/2, 0],
              [1/3, 1/2, 0, 1, 0, 1/2],
              [1/3, 0, 1/3, 0, 1/2, 1/2],
              [0, 0, 0, 0, 0, 0],
              [0, 0, 1/3, 0, 0, 0]])
r = 100 * np.ones(6) / 6
print(r)

for i in np.arange(100):
    r = L @ r

print(r)  

r = 100 * np.ones(6) / 6
lastR = r
r = L @ r

i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = L @ r
    i += 1

print(f"{i} iterations to convergence.")
print(r)

L2 = np.array([[0, 1/2, 1/3, 0, 0, 0, 0],
               [1/3, 0, 0, 0, 1/2, 0, 0],
               [1/3, 1/2, 0, 1, 0, 0, 0],
               [1/3, 0, 1/3, 0, 1/2, 0, 0],
               [0, 0, 0, 0, 0, 0, 0],
               [0, 0, 1/3, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 0, 1]])

d = 0.8
M = d * L2 + (1 - d) / 7 * np.ones([7, 7]) 
r = 100 * np.ones(7) / 7
lastR = r
r = L2 @ r

i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = L2 @ r
    i += 1

print(f"{i} iterations to convergence.")
print(r)

d = 0.8
M = d * L2 + (1 - d) / 7 * np.ones([7, 7])

r = 100 * np.ones(7) / 7
lastR = r
r = M @ r

i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = M @ r
    i += 1

print(f"{i} iterations to convergence.")
print(r)


[16.66666667 16.66666667 16.66666667 16.66666667 16.66666667 16.66666667]
[16.          5.33333333 40.         25.33333333  0.         13.33333333]
18 iterations to convergence.
[16.00149917  5.33252025 39.99916911 25.3324738   0.         13.33433767]
46 iterations to convergence.
[1.07742874e-02 4.20323681e-03 2.13132105e-02 1.25178906e-02
 0.00000000e+00 8.56654771e+01 1.42857143e+01]
19 iterations to convergence.
[10.15892915  6.7094426  17.3137475  11.32722084  2.85714286 37.34780278
 14.28571429]
