In [1]:
import numpy as np
import numpy.linalg as la

L = np.array([[0, 1/2, 1/3, 0, 0, 0],
              [1/3, 0, 0, 0, 1/2, 0],
              [1/3, 1/2, 0, 1, 0, 1/2],
              [1/3, 0, 1/3, 0, 1/2, 1/2],
              [0, 0, 0, 0, 0, 0],
              [0, 0, 1/3, 0, 0, 0]])

r = 100 * np.ones(6) / 6 
print(r)

for i in np.arange(100):
    r = L @ r

print(r)

r = 100 * np.ones(6) / 6  
lastR = r
r = L @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = L @ r
    i += 1

print(f"{i} iterations to convergence.")
print(r)

L2 = np.array([[0, 1/2, 1/3, 0, 0, 0, 0],
               [1/3, 0, 0, 0, 1/2, 0, 0],
               [1/3, 1/2, 0, 1, 0, 0, 0],
               [1/3, 0, 1/3, 0, 1/2, 0, 0],
               [0, 0, 0, 0, 0, 0, 0],
               [0, 0, 1/3, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 0, 1]])

d = 0.8
M = d * L2 + (1-d)/7 * np.ones([7, 7]) 
r = 100 * np.ones(7) / 7  
lastR = r
r = L2 @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = L2 @ r
    i += 1

print(f"{i} iterations to convergence.")
print(r)
r = 100 * np.ones(7) / 7 
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = M @ r
    i += 1

print(f"{i} iterations to convergence.")
print(r)


[16.66666667 16.66666667 16.66666667 16.66666667 16.66666667 16.66666667]
[16.          5.33333333 40.         25.33333333  0.         13.33333333]
18 iterations to convergence.
[16.00149917  5.33252025 39.99916911 25.3324738   0.         13.33433767]
46 iterations to convergence.
[1.07742874e-02 4.20323681e-03 2.13132105e-02 1.25178906e-02
 0.00000000e+00 8.56654771e+01 1.42857143e+01]
19 iterations to convergence.
[10.15892915  6.7094426  17.3137475  11.32722084  2.85714286 37.34780278
 14.28571429]


In [3]:
import numpy as np
import numpy.linalg as la

graph = {
    0: [1, 2],      
    1: [0, 4],     
    2: [0, 1, 3, 5],
    3: [0, 2, 4, 5],
    4: [],          
    5: [2]          
}
n = len(graph)  
L = np.zeros((n, n)) 

for j in graph:
    outgoing_links = graph[j]
    if outgoing_links:
        prob = 1 / len(outgoing_links)
        for i in outgoing_links:
            L[i, j] = prob  
r = 100 * np.ones(n) / n 
print("Initial rank vector:", r)
lastR = r
r = L @ r
i = 0
while la.norm(lastR - r) > 0.01:  
    lastR = r
    r = L @ r
    i += 1

print(f"{i} iterations to convergence.")
print("Final rank vector:", r)

d = 0.8
M = d * L + (1 - d) / n * np.ones([n, n]) 
r = 100 * np.ones(n) / n  

lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01:
    lastR = r
    r = M @ r
    i += 1

print(f"{i} iterations to convergence with damping factor.")
print("Final rank vector with damping factor:", r)


Initial rank vector: [16.66666667 16.66666667 16.66666667 16.66666667 16.66666667 16.66666667]
43 iterations to convergence.
Final rank vector: [0.02786592 0.02605531 0.0338586  0.00984699 0.01801893 0.01271076]
51 iterations to convergence with damping factor.
Final rank vector with damping factor: [0.0348944  0.0323188  0.04437063 0.01655074 0.02486932 0.02029021]
